config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts, except: :index
  resources :user, only: :show
  resources :profiles, only: [:show, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :age, :gender, :last_name, :first_name, :height, :weight, :foot_size, :address, :skill, :favorite_food, :introduction, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.inclubes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params(hoge)
    params.require(:post).permit(:title, :cohtent).merge(user_id: current_user.id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to user_path(current_user)
    else
      @error = "登録に失敗しました。"
      render action: :new
    end
  end

  def edit
    @profile = Profile.find(current_user.profile.id)
  end

  def update
    @profile = Profile.find(params[:id])
    if Profile.update(profile_params)
      redirect_to user_path(current_user)
    else
      @error = "登録に失敗しました。"
      render action: :edit
    end
  end

  def destroy
    @profile = current_user.profile
    @profile.destroy
    redirect_to user_path(current_user)
  end


  private

  def profile_params
    params.require(:profile).permit(:age, :gender, :last_name, :first_name, :height, :weight, :foot_size, :address, :skill, :favorite_food, :introduction).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OurBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="header">
    <div class="header__title">
      <%= link_to "Our Blog", root_path, class: "header__title--text" %>
    </div>
    <div class="header__right">
    <% if user_signed_in? %>
        <%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>
        <%= link_to "新規投稿", "/post/new", class: "header__right--btn" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
      <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
    <% end %>
    </div>
  </header>
  <body>
    <div class="contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.htm.erb
<div class="content__title">
  投稿の編集
</div>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/index.html.erb
<% @post.each do |post| %>
  <%= render partial: "post", locals: { post: post } %>
<% end %>

app/views/posts/new.html.erb
<div class="content__title">
  新規記事の作成
</div>

<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title, name: "" %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/post.html.erb
<div class="content">
  <div class="content__left">
    <div class="content__left--image"></div>
  </div>
  <div class="content__right">
    <div class="content__right__top">
      <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %>
    </div>
    <div class="content__right__bottom">
      <div class="content__right__bottom--userName">
        <%= link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn" %>
      </div>
      <div class="content__right__bottom--date">
        <%= post.created_at %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="postTitle">
  <%= @post.title %>
</div>
<div class="postDate">
  <%= @post.created_at %>
</div>
<div class="postAuthor">
</div>
<% if user_signed_in? && current_user.id == @post.user_id %>
  <div class="postManage">
    <%= link_to "編集", edit_post_path(@post.id), class: "postManage__edit" %>
    <%= link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete" %>
  </div>
<% end %>
<div class="postText">
  <%= simple_format @post.content %>
</div>

app/views/profiles/edit.html.erb
<div class="content__title">
  プロフィール編集
</div>

<div class="profile-errors">
  <% if @error%>
    <h3 class="profile-errors-title"><%= @error%></h3>
  <% end%>
</div>

<div class="profile-form">

  <%= form_with model: @profile, class: :form, local: true do |form| %>
    <%= form.label :name, "年齢" %>
    <%= form.number_field :age, placeholder: :年齢, class: "narrow-form" %>

    <%= form.label :name, "性別" %>
    <%= form.text_field :gender, placeholder: :性別, class: "narrow-form" %>

    <%= form.label :last_name, "名字" %>
    <%= form.text_field :last_name, placeholder: :名字, class: "narrow-form" %>

    <%= form.label :first_name, "名前" %>
    <%= form.text_field :first_name, placeholder: :名前, class: "narrow-form" %>

    <%= form.label :height, "身長（cm）" %>
    <%= form.text_field :height, placeholder: :身長, class: "narrow-form" %>

    <%= form.label :weight, "体重（kg）" %>
    <%= form.text_field :weight, placeholder: :体重, class: "narrow-form" %>

    <%= form.label :foot_size, "靴のサイズ（cm）" %>
    <%= form.text_field :foot_size, placeholder: :靴のサイズ, class: "narrow-form" %>

    <%= form.label :address, "住所" %>
    <%= form.text_field :address, placeholder: :住所, class: "wide-form" %>

    <%= form.label :skill, "特技" %>
    <%= form.text_field :skill, placeholder: :特技, class: "wide-form" %>

    <%= form.label :favorite_food, "好きな食べ物" %>
    <%= form.text_field :favorite_food, placeholder: :好きな食べ物, class: "narrow-form" %>

    <%= form.label :introduction, "自己紹介" %>
    <%= form.text_area :introduction, placeholder: :自己紹介, class: :form__text %>

    <%= form.submit '登録する', class: :form__btn %>
  <% end %>

</div>

app/views/profiles/new.html.erb
<div class="content__title">
  プロフィール編集
</div>

<div class="profile-errors">
  <% if @error%>
    <h3 class="profile-errors-title"><%= @error%></h3>
  <% end%>
</div>

<div class="profile-form">

  <%= form_with model: @profile, class: :form, local: true do |form| %>

    <%= form.submit '登録する', class: :form__btn %>

    <%= form.label :name, "年齢" %>
    <%= form.number_field :age, placeholder: :年齢, value: "20", class: "narrow-form" %>

    <%= form.label :gender, "性別" %>
    <%= form.text_field :gander, placeholder: :性別, value: "男性", class: "narrow-form" %>

    <%= form.label :last_name, "名字" %>
    <%= form.text_field :last_name, placeholder: :名字,  value: "山田", class: "narrow-form" %>

    <%= form.label :first_name, "名前" %>
    <%= form.text_field :first_name, placeholder: :名前, value: "太郎", class: "narrow-form" %>

    <%= form.label :height, "身長（cm）" %>
    <%= form.text_field :height, placeholder: :身長, value:"170", class: "narrow-form" %>

    <%= form.label :weight, "体重（kg）" %>
    <%= form.text_field :weight, placeholder: :体重, value: "65", class: "narrow-form" %>

    <%= form.label :foot_size, "靴のサイズ（cm）" %>
    <%= form.text_field :foot_size, placeholder: :靴のサイズ, value: "27", class: "narrow-form" %>

    <%= form.label :address, "住所" %>
    <%= form.text_field :address, placeholder: :住所, value: "大阪府テック市エキスパート町", class: "wide-form" %>

    <%= form.label :skill, "特技" %>
    <%= form.text_field :skill, placeholder: :特技, value: "プログラミング", class: "wide-form" %>

    <%= form.label :favorite_food, "好きな食べ物" %>
    <%= form.text_field :favorite_food, placeholder: :好きな食べ物, value: "カレーライス", class: "narrow-form" %>

    <%= form.label :introduction, "自己紹介" %>
    <%= form.text_area :introduction, placeholder: :自己紹介, value: "エンジニアになりたい！", class: :form__text %>

  <% end %>

</div>

app/views/users/show.html.erb
<div class="users-wrapper">
  <div class="users-content">
    <div class="postTitle">
      <%= @user.nickname %>さんの投稿一覧
    </div>
    <% @user.posts.each do |post| %>
      <%= render partial: "posts/post", locals: { post: post } %>
    <% end %>
  </div>

  <div class="profile-content">
    <h3 class="profile-header">
      <%= current_user.nickname%>さんのプロフィール
    </h3>
    <% if current_user.profile%>
      <div class="profile">
        <span class="profile-left">
          年齢：
        </span>
        <%= current_user.profile.age%>歳
      </div>

      <div class="profile">
        <span class="profile-left">
          性別：
        </span>
        <%= current_user.profile.gender%>
      </div>

      <div class="profile">
        <span class="profile-left">
          名前：
        </span>
        <%= current_user.profile.last_name%><%= current_user.profile.first_name%>
      </div>

      <div class="profile">
        <span class="profile-left">
          身長：
        </span>
        <%= current_user.profile.height%>cm
      </div>

      <div class="profile">
        <span class="profile-left">
          体重：
        </span>
        <%= current_user.profile.weight%>kg
      </div>

      <div class="profile">
        <span class="profile-left">
          靴のサイズ：
        </span>
        <%= current_user.profile.foot_size%>cm
      </div>

      <div class="profile">
        <span class="profile-left">
          住所：
        </span>
        <%= current_user.profile.address%>
      </div>

      <div class="profile">
        <span class="profile-left">
          特技：
        </span>
        <%= current_user.profile.skill%>
      </div>

      <div class="profile">
        <span class="profile-left">
          好きな食べ物：
        </span>
        <%= current_user.profile.favorite_food%>
      </div>

      <div class="profile">
        <span class="profile-left">
          自己紹介：
        </span>
      <%= current_user.profile.introduction%>

      <br>
      <%= link_to "プロフィールを編集する", edit_profile_path(current_user.profile), class: "profile-btn" %>
      <br>
      <%= link_to "プロフィールを削除する", profile_path, method: :delete, class: "profile-btn" %>
      </div>

    <% else %>
      <%= link_to "プロフィールを登録する", new_profile_path, class: "profile-btn" %>
    <% end %>
  </div>
</div>